- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps"
    DURATION: "2 YEAR"
    EMPLOYEE: "Ranjith"
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am working in {{COURSE}}, Duration is: {{DURATION}}, Employee: {{EMPLOYEE}}"