- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
     msg: "Hello {{ name }}"

    loops:
    - Ramesh
    - Suresh
    - Dinesh
    - Raheem   