- name: install nginx and run
  hosts: web
  become: yes #take sudo access
  tasks: 
  - name: nginx
    ansible.builtin.package:  #heterogeneous module that can work for all distros
      name: nginx
      state: present


- name: run nginx
  ansible.builtin.service:
    name: nginx
    state: started      
    enabled: yes